import os

# API Configuration
OANDA_ACCESS_TOKEN = os.getenv("OANDA_ACCESS_TOKEN", "YOUR_TOKEN_HERE")
OANDA_ACCOUNT_ID = os.getenv("OANDA_ACCOUNT_ID", "YOUR_ACCOUNT_ID_HERE")
OANDA_ENVIRONMENT = os.getenv("OANDA_ENVIRONMENT", "practice")  # practice or live

# Strategy Parameters
TIMEFRAME_1H = "1H"
TIMEFRAME_4H = "4H"

# Supertrend
SUPERTREND_LENGTH = 10
SUPERTREND_MULTIPLIER = 3.0

# StochRSI
STOCHRSI_LENGTH = 14
STOCHRSI_RSI_LENGTH = 14
STOCHRSI_K = 3
STOCHRSI_D = 3
STOCHRSI_OVERSOLD = 30
STOCHRSI_OVERBOUGHT = 70

# Risk Management
MAX_RISK_PCT = 0.02
MAX_EXPOSURE_PCT = 0.06
