/**
 * Re-cost report (work plan 2026-09-25 P0.3 / P1.4): logged vs real-fee P&L
 * per exit reason, cohort and hold bucket, with seeded bootstrap CIs.
 * Deterministic for a given (input, seed).
 */
import { createHash } from 'node:crypto';
import {
  byExitReason,
  cohortRows,
  grossPct,
  HOLD_BUCKETS,
  recostTrade,
  STANDARD_COHORTS,
  type CohortRow,
  type Trade,
} from './trades.ts';
import { median, sum, summarize } from './stats.ts';

export interface RecostOptions {
  seed: number;
  /** swapFeePct the export was logged with (config.fees.swapFeePct at the time). */
  loggedSwapFeePct: number;
  iterations?: number;
}

export interface RecostTotals {
  n: number;
  turnoverSol: number;
  loggedNetSol: number;
  recostNetSol: number;
  loggedNetPctTurnover: number;
  recostNetPctTurnover: number;
  loggedNetPctMean: number;
  recostNetPctMean: number;
  grossPctMean: number;
  grossCI: { lo: number; hi: number };
  recostCI: { lo: number; hi: number };
  winRate: number;
  avgWinPct: number;
  avgLossPct: number;
  breakevenWinRate: number;
  swapFeesSol: number;
  txCostsSol: number;
  slippageSol: number;
}

export function recostTotals(trades: readonly Trade[], o: RecostOptions): RecostTotals {
  const it = o.iterations ?? 10_000;
  const rc = trades.map((t) => recostTrade(t, o));
  const turnover = sum(trades.map((t) => t.sizeSol));
  const loggedNet = sum(trades.map((t) => t.netPnlSol));
  const recostNet = sum(rc.map((r) => r.netPnlSol));
  const netPcts = trades.map((t) => (t.netPnlSol / t.sizeSol) * 100);
  const rcPcts = rc.map((r, i) => (r.netPnlSol / trades[i]!.sizeSol) * 100);
  const g = summarize(trades.map(grossPct), o.seed, it);
  const r = summarize(rcPcts, o.seed, it);
  const n = summarize(netPcts, o.seed, it);
  return {
    n: trades.length,
    turnoverSol: turnover,
    loggedNetSol: loggedNet,
    recostNetSol: recostNet,
    loggedNetPctTurnover: (loggedNet / turnover) * 100,
    recostNetPctTurnover: (recostNet / turnover) * 100,
    loggedNetPctMean: n.mean,
    recostNetPctMean: r.mean,
    grossPctMean: g.mean,
    grossCI: { lo: g.meanCI.lo, hi: g.meanCI.hi },
    recostCI: { lo: r.meanCI.lo, hi: r.meanCI.hi },
    winRate: n.winRate,
    avgWinPct: n.avgWin,
    avgLossPct: n.avgLoss,
    breakevenWinRate: n.breakevenWinRate,
    swapFeesSol: sum(rc.map((x) => x.swapFeesSol)),
    txCostsSol: sum(rc.map((x) => x.txCostsSol)),
    slippageSol: sum(trades.map((t) => t.slippageSol)),
  };
}

const f = (x: number, d = 2) => (Number.isFinite(x) ? x.toFixed(d) : '—');
const sgn = (x: number, d = 3) => (Number.isFinite(x) ? `${x >= 0 ? '+' : '−'}${Math.abs(x).toFixed(d)}` : '—');
const pct = (x: number) => (Number.isFinite(x) ? `${(x * 100).toFixed(1)} %` : '—');

function cohortTable(rows: readonly CohortRow[]): string {
  const head =
    '| Cohort | n | Gross %/trade [95 % CI] | Net % (logged) | Net % (real fees) | Net SOL (logged) | Net SOL (real fees) | WR (logged) | WR (real fees) |\n' +
    '|---|---|---|---|---|---|---|---|---|';
  const body = rows
    .filter((r) => r.n > 0)
    .map(
      (r) =>
        `| ${r.name} | ${r.n} | ${sgn(r.grossPct.mean, 2)} [${sgn(r.grossPct.meanCI.lo, 1)}, ${sgn(r.grossPct.meanCI.hi, 1)}] | ${sgn(r.netPct, 2)} | ${sgn(r.recostNetPct, 2)} | ${sgn(r.netSol)} | ${sgn(r.recostNetSol)} | ${pct(r.winRate)} | ${pct(r.recostWinRate)} |`,
    );
  return [head, ...body].join('\n');
}

function exitReasonTable(trades: readonly Trade[], o: RecostOptions): string {
  const head =
    '| Exit reason | n | Net SOL (logged) | Net SOL (real fees) | Avg net % (logged) | Gross median % | MFE avg % | Median hold |\n' +
    '|---|---|---|---|---|---|---|---|';
  const rows = byExitReason(trades).map((c) => {
    const ts = trades.filter(c.test);
    const rc = ts.map((t) => recostTrade(t, o).netPnlSol);
    const mfe = ts.map((t) => t.mfePct ?? NaN).filter(Number.isFinite);
    const hold = ts.map((t) => t.holdMs ?? NaN).filter(Number.isFinite);
    return `| ${c.name} | ${ts.length} | ${sgn(sum(ts.map((t) => t.netPnlSol)))} | ${sgn(sum(rc))} | ${sgn(
      sum(ts.map((t) => (t.netPnlSol / t.sizeSol) * 100)) / ts.length,
      1,
    )} | ${sgn(median(ts.map(grossPct)), 1)} | ${f(mfe.length ? sum(mfe) / mfe.length : NaN, 1)} | ${f(median(hold) / 1000, 1)} s |`;
  });
  return [head, ...rows].join('\n');
}

export function renderRecostReport(
  trades: readonly Trade[],
  o: RecostOptions & { title: string; source: string; sourceSha256: string; preamble?: string },
): string {
  const t = recostTotals(trades, o);
  const it = o.iterations ?? 5_000;
  const recost = (x: Trade) => recostTrade(x, o).netPnlSol;
  const lines = [
    `# ${o.title}`,
    '',
    `Source: \`${o.source}\` · sha256 \`${o.sourceSha256}\` · seed ${o.seed} · generated by \`npm run research:recost\``,
    '',
    ...(o.preamble ? [o.preamble, ''] : []),
    '## Totals',
    '',
    '| Metric | Value |',
    '|---|---|',
    `| Trades | ${t.n} |`,
    `| Turnover | ${f(t.turnoverSol, 3)} SOL |`,
    `| Net P&L — logged | ${sgn(t.loggedNetSol)} SOL (${sgn(t.loggedNetPctTurnover, 2)} % of turnover; ${sgn(t.loggedNetPctMean, 2)} %/trade mean) |`,
    `| Net P&L — real PumpSwap fees | **${sgn(t.recostNetSol)} SOL** (${sgn(t.recostNetPctTurnover, 2)} % of turnover; ${sgn(t.recostNetPctMean, 2)} %/trade mean, 95 % CI [${sgn(t.recostCI.lo, 2)}, ${sgn(t.recostCI.hi, 2)}]) |`,
    `| Gross (pre-fee) expectancy | ${sgn(t.grossPctMean, 2)} %/trade, 95 % bootstrap CI [${sgn(t.grossCI.lo, 2)}, ${sgn(t.grossCI.hi, 2)}] |`,
    `| Win rate (logged net) | ${pct(t.winRate)} · avg win ${sgn(t.avgWinPct, 1)} % · avg loss ${sgn(t.avgLossPct, 1)} % · breakeven WR ${pct(t.breakevenWinRate)} |`,
    `| Real swap fees / tx costs / modelled impact | ${f(t.swapFeesSol, 4)} / ${f(t.txCostsSol, 4)} / ${f(t.slippageSol, 4)} SOL |`,
    '',
    `Re-cost method: logged swap fee (${o.loggedSwapFeePct} %/leg) replaced by the PumpSwap canonical tier schedule, per leg, entry on size and exit on proceeds; mcap per leg = price × 1e9 supply; tx costs and modelled impact kept as logged (\`src/research/trades.ts:recostTrade\`).`,
    '',
    '## By exit reason',
    '',
    exitReasonTable(trades, o),
    '',
    '## By cohort',
    '',
    cohortTable(cohortRows(trades, STANDARD_COHORTS, recost, o.seed, it)),
    '',
    '## By hold time',
    '',
    cohortTable(cohortRows(trades, HOLD_BUCKETS, recost, o.seed, it)),
    '',
  ];
  return lines.join('\n');
}

export function sha256(text: string): string {
  return createHash('sha256').update(text).digest('hex');
}
